version: "3"

services:
  postgres:
    container_name: vortexcore-be-postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - vex-network
    restart: unless-stopped

  redis:
    container_name: vortexcore-be-redis
    image: redis/redis-stack-server:7.2.0-v9
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    networks:
      - vex-network
    restart: unless-stopped

  vault:
    container_name: vortexcore-be-vault
    image: vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
    ports:
      - "8200:8200"
    networks:
      - vex-network
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    cap_add:
      - IPC_LOCK

  strapi:
    container_name: vortexcore-be-strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DB_CLIENT}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DB_POST}
      DATABASE_NAME: dev_strapi
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - vex-network
    depends_on:
      - postgres
      - redis

  account-svc:
    container_name: vortexcore-be-account
    image: dodyy14/vortex-be-account:latest
    env_file:
      - .env
    environment:
      DATABASE_NAME: dev_account
    ports:
      - "3011:3011"
    networks:
      - vex-network
    depends_on:
      - redis
      - postgres
      - vault
    restart: always

networks:
  vex-network:
    driver: bridge
