version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - vex-network
    restart: always

  redis:
    image: redis/redis-stack-server:latest
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    networks:
      - vex-network
    restart: always

  vault:
    image: vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
    ports:
      - "8200:8200"
    networks:
      - vex-network
    depends_on:
      - redis
      - postgres
    restart: always
    cap_add:
      - IPC_LOCK

networks:
  vex-network:
    driver: bridge
